 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: pretrain_chatglm6b
  load_finetuned: False

  pretrained: "lavis/output/BLIP2/Pretrain_stage2/20230327161/checkpoint_9.pth"
  finetuned: ""

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  vit_model: clip_L
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # OPT
  lm_model: "/home/wsh/models/chatglm-6b"

  # generation configs
  prompt: ""
  use_prompt: False


preprocess:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
