 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: vqa
  load_finetuned: True

  pretrained: "lavis/output/BLIP2/Pretrain_stage2/20230411095/checkpoint_37500.pth"
  finetuned: "lavis/output/BLIP2/vqa_ft/20230413235/checkpoint_4.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # OPT
  lm_model: "/home/wsh/models/chatglm-6b"

  # generation configs


preprocess:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
